### ISSUE TITLE
Missing German translations in web-ui in v6

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-i18n#100]
- where to find: https://127.0.0.1:5000/uploads
![upload_9c66d7fcc0c40d8b2a2ef79a2a931f5d](https://user-images.githubusercontent.com/74763324/142225498-981fb414-585f-4826-96a2-dcd7fc967a12.png)
  - [x] 'No description'
  - https://github.com/search?q=org%3Ainveniosoftware+%22No+description%22&type=Code
    - Maybe: https://github.com/inveniosoftware/invenio-app-rdm/blob/master/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/search/components.js

---

- where to find: --- use your own record id--- https://127.0.0.1:5000/records/b4b3y-7z206
![upload_fe562e2f662598921b4f9136a4e70088](https://user-images.githubusercontent.com/74763324/142225759-c0f64a93-8c99-4983-ad76-f348ff0567f6.png)
  - [ ] Contact person(s)
  - [ ] Data collector(s)
  - [ ] Other(s)
  - https://github.com/search?q=org%3Ainveniosoftware+%22Contact+person%22&type=Code
    - invenio_rdm_records/fixtures/data/vocabularies/roles.yaml
    - Vocabularies?

---

- where to find: --- if you do not have an abc.html --- https://127.0.0.1:5000/abc
![upload_b891d3cab96b3fad571658fb3acec48c](https://user-images.githubusercontent.com/74763324/142226268-0a1f3a76-cff9-4acf-ab58-a7e766e018a3.png)
  - [x] Page not found
  - Not used? https://github.com/inveniosoftware/invenio-theme/blob/master/invenio_theme/translations/de/LC_MESSAGES/messages.po#L51-L54

---

- where to find: https://127.0.0.1:5000/search

![upload_312f64d7d67a14435e370bbd3e246a3b](https://user-images.githubusercontent.com/74763324/142226699-713e7840-22a1-452c-aad0-dce7f9c203e1.png)
![upload_013d990a1eb5535387987740931efc29](https://user-images.githubusercontent.com/74763324/142226782-b11f1b22-ccb6-42e5-8b22-4a2c3452fbbe.png)

  - [x] Drop down: Best match, Newest, Oldest, Version
    -   https://github.com/search?q=org%3Ainveniosoftware+%22Best+match%22&type=Code
  - [ ] Left Site: Access status, Resource types, Publication, Other, ...
    - https://github.com/search?p=1&q=org%3Ainveniosoftware+%22Access+status%22&type=Code
  - [ ] grey tag: Figure, Other, Visual/Audio, ... 
  - [ ] 100 'result(s) found' (interestingly in the uploads it is translated)
  - [ ] 10 results per page (interestingly in the uploads it is translated)

----

- where to find: https://127.0.0.1:5000/uploads
![upload_9c66d7fcc0c40d8b2a2ef79a2a931f5d](https://user-images.githubusercontent.com/74763324/142230291-3c079ad4-15c9-4a08-b6be-033da905240e.png)
  - [x] Drop down: recently updated; best match; ...
  - [ ] Left site: Access status, Metadata-only, Unpublished, (and most other stuff not shown in this screenshot)
       - https://github.com/search?p=1&q=org%3Ainveniosoftware+%22Access+status%22&type=Code

----

- where to find: https://127.0.0.1:5000/search (when something goes wrong internally)
![upload_a02a651772b0142dfb2c61ddc24e2a3f](https://user-images.githubusercontent.com/74763324/142233353-502c68eb-783a-4e45-b36e-d64b138d9727.png)
  - [ ] Untranslated - maybe from react-searchkit?
  - https://discord.com/channels/692989811736182844/852219787005919242/902550763706937344
  - https://discord.com/channels/692989811736182844/852219787005919242/902831642253590569
----

Subissue for https://127.0.0.1:5000/uploads/new is [here](https://github.com/inveniosoftware/invenio-i18n/issues/102)

**Comment by mb-wali** [comment]
closing since most of them has been fixed, remains are vocabularies related strings which we opened an issue https://github.com/inveniosoftware/invenio-app-rdm/issues/1306
