### ISSUE TITLE
Missing German translations in web-ui in v6 - uploads/new

### ISSUE THREAD

**Issue by chriz-uniba** [inveniosoftware/invenio-i18n#102]
Subissue of #100 only taking a look at creating a new record

where to find: https://127.0.0.1:5000/uploads/new

---
![upload_8436a3bb4bad5359ecbcbaa716c1919c](https://user-images.githubusercontent.com/74763324/143014259-f51c27e5-7511-44ce-8e9e-d13b08a5b20e.png)
- [x] "Disable files for this record"
  - https://github.com/search?q=org%3Ainveniosoftware+Disable+files+for+this+record
  - Maybe here: https://github.com/inveniosoftware/react-invenio-deposit/blob/master/src/lib/components/FileUploader/FileUploaderToolbar.js#L43

---

![upload_d1a4a71023b38f4d5cf49b4632880915](https://user-images.githubusercontent.com/74763324/143015142-47d5a9bb-b43b-471a-874c-1d9bc3d8fb2e.png)
- [ ] "Additional title" / "Type" / "Language" (titles/headdings/field labels)
- [ ] dropdown-menu
  - https://github.com/search?q=org%3Ainveniosoftware+Translated+title
  - Maybe here: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/title_types.yaml

---

![upload_b751d4bc079950dae2d3de88d909a121](https://user-images.githubusercontent.com/74763324/143017825-e07697fc-b4fc-417d-8d41-f59294b5e8dc.png)
- [ ] Paragraph/Heading 1/2/3
- [ ] hover over tool tips 

---

![upload_4fe73a0db75d296764f44a6c84f1e5b1](https://user-images.githubusercontent.com/74763324/143018083-b8e3f22f-5a05-4ffb-bdd9-82477b60ccb0.png)
- [x] Add creator (title)
  - https://github.com/search?q=org%3Ainveniosoftware+%22Add+creator%22
  - Maybe: https://github.com/inveniosoftware/react-invenio-deposit/blob/master/src/lib/components/Creatibutors/CreatibutorsField.js#L182

---

![upload_9ee9e20644944dce4672a91cab4685ce](https://user-images.githubusercontent.com/74763324/143019375-30c4c66c-c466-4706-8d04-9da7e1e2c710.png)
- [ ] Roles
  - https://github.com/search?q=org%3Ainveniosoftware+%22Hosting+institution%22
  - Maybe https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/roles.yaml

---

![upload_84c7617982682e40494840721f3dd6f6](https://user-images.githubusercontent.com/74763324/143019737-70613d95-35c9-49b6-9377-d82e6393b819.png)
- [x] Add standard license (title)
- [x] 'Search' (in the search field)

---

![upload_38913cb526bc3a794ba5dc4997bbad7f](https://user-images.githubusercontent.com/74763324/143020224-51b1c9fa-efb9-4aa6-9b65-877fcaec852f.png)
- [x] Add custom license (title) 

---

![upload_862d5d768e2e657cc76eb66a1be8c758](https://user-images.githubusercontent.com/74763324/143020432-4145f0f7-967e-4630-8283-23c414f7e6a0.png)
- [ ] Dropdown 'type of description;
  - https://github.com/search?q=org%3Ainveniosoftware+%22Table+of+contents%22
  - Maybe: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/description_types.yaml

---

![upload_e35c05d5705c1069742a8d27f7169b12](https://user-images.githubusercontent.com/74763324/143020873-5bf49b98-03a2-4978-aa16-fdb9504aee64.png)
- [ ] Dropdown 'All"

---

![upload_2d606a66a63031e286df2b2da7666939](https://user-images.githubusercontent.com/74763324/143021072-a05ddb7c-fceb-4cae-b139-2f84dd851c01.png)
- [ ] Dropdown "type" of date
  - https://github.com/search?q=org%3Ainveniosoftware+%22Copyrighted%22
  - Maybe: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/date_types.yaml

---

![upload_e43093cb1285b127c9de46942d8b1e5f](https://user-images.githubusercontent.com/74763324/143021416-364dd5c3-4b91-49f3-8784-1d3229b503e7.png)
- [ ] Dropdown 'related work'
  - https://github.com/search?q=org%3Ainveniosoftware+%22Is+cited+by%22
  - Maybe: https://github.com/inveniosoftware/invenio-rdm-records/blob/master/invenio_rdm_records/fixtures/data/vocabularies/relation_types.yaml

**Comment by mb-wali** [comment]
closing since most of them has been fixed, remains are vocabularies related strings which we opened an issue inveniosoftware/invenio-app-rdm#1306
