### ISSUE TITLE
i18n workflow: force compile fuzzy

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-i18n#103]
In order to compile fuzzy marked strings, we need to force it.
todoso we have to add this line `use-fuzzy = True` to the `[compile_catalog]` section of `setup.cfg` file.

This should be added  to the following modules:
- [x] [invenio-i18n](https://github.com/inveniosoftware/invenio-i18n)
- [x] [invenio-app-rdm](https://github.com/inveniosoftware/invenio-app-rdm)
- [ ] [invenio-access](https://github.com/inveniosoftware/invenio-access)
- [x] [invenio-accounts](https://github.com/inveniosoftware/invenio-accounts)
- [ ] [invenio-app](https://github.com/inveniosoftware/invenio-app)
- [ ] [invenio-assets](https://github.com/inveniosoftware/invenio-assets)
- [ ] [invenio-base](https://github.com/inveniosoftware/invenio-base)
- [ ] [invenio-cache](https://github.com/inveniosoftware/invenio-cache)
- [ ] [invenio-celery](https://github.com/inveniosoftware/invenio-celery)
- [x] [invenio-communities](https://github.com/inveniosoftware/invenio-communities)
- [ ] [invenio-config](https://github.com/inveniosoftware/invenio-config)
- [ ] [invenio-db](https://github.com/inveniosoftware/invenio-db)
- [x] [invenio-drafts-resources](https://github.com/inveniosoftware/invenio-drafts-resources)
- [ ] [invenio-config](https://github.com/inveniosoftware/invenio-config)
- [ ] [invenio-formatter](https://github.com/inveniosoftware/invenio-config)
- [x] [invenio-files-rest](https://github.com/inveniosoftware/invenio-files-rest)
- [ ] [invenio-iiif](https://github.com/inveniosoftware/invenio-iiif )
- [ ] [invenio-indexer](https://github.com/inveniosoftware/invenio-indexer)
- [ ] [invenio-jsonschemas](https://github.com/inveniosoftware/invenio-jsonschemas)
- [ ] [invenio-logging](https://github.com/inveniosoftware/invenio-logging)
- [ ] [invenio-mail](https://github.com/inveniosoftware/invenio-mail)
- [x] [invenio-oaiserver](https://github.com/inveniosoftware/invenio-oaiserver)
- [x] [invenio-oauth2server](https://github.com/inveniosoftware/invenio-oauth2server)
- [x] [invenio-oauthclient](https://github.com/inveniosoftware/invenio-oauthclient)
- [x] [invenio-pidstore](https://github.com/inveniosoftware/invenio-pidstore)
- [ ] [invenio-previewer](https://github.com/inveniosoftware/invenio-previewer)
- [x] [invenio-rdm-records](https://github.com/inveniosoftware/invenio-rdm-records)
- [ ] [invenio-records](https://github.com/inveniosoftware/invenio-records)
- [ ] [invenio-records-files](https://github.com/inveniosoftware/invenio-records-files)
- [x] [invenio-records-permissions](https://github.com/inveniosoftware/invenio-records-permissions)
- [x] [invenio-records-resources](https://github.com/inveniosoftware/invenio-records-resources)
- [ ] [invenio-records-rest](https://github.com/inveniosoftware/invenio-records-rest)
- [ ] [invenio-rest](https://github.com/inveniosoftware/invenio-rest)
- [ ] [invenio-saml](https://github.com/inveniosoftware/invenio-saml)
- [x] [invenio-search-ui](https://github.com/inveniosoftware/invenio-search-ui)
- [x] [invenio-theme](https://github.com/inveniosoftware/invenio-theme)
- [x] [invenio-userprofiles](https://github.com/inveniosoftware/invenio-userprofiles)
- [x] [invenio-vocabularies](https://github.com/inveniosoftware/invenio-vocabularies)
- [x] [cookiecutter-invenio-rdm](https://github.com/inveniosoftware/cookiecutter-invenio-rdm)
- [x] [cookiecutter-invenio-module](https://github.com/inveniosoftware/cookiecutter-invenio-module)
- [x] [marshmallow-utils](https://github.com/inveniosoftware/marshmallow-utils)
- [x] [invenio-requests](https://github.com/inveniosoftware/invenio-requests)
- [x] [invenio-users-resources](https://github.com/inveniosoftware/invenio-users-resources)

Close related issue #inveniosoftware/invenio-app-rdm/issues/230

**Comment by chriz-uniba** [comment]
Can we check the status of this issue?

1. based on this list it seems, that we have packages where we force fuzzy and packages, where this is not the case. Is this information still correct?

2. since this lists is already some days old, I remember, that there were new packages added, what's the status with these? The documentation mentions the `fuzzy`: https://inveniordm.docs.cern.ch/develop/howtos/i18n/#configuration
Related: https://github.com/inveniosoftware/invenio-i18n/issues/99

3. are we sure that we need/want to force it?
   - Maybe there is a better way, by fixing fuzzy (when using transifex)?

- I can/will try to check transifex in the upcoming weeks.
- I would be happy to get some opinions/experience of the `force-use`.
  Maybe: @utnapischtim @rekt-hard @zzacharo 

- When discussed point 3. I could try to get the changes in all packages.

**Comment by rekt-hard** [comment]
1. All packages which contain translatable strings should force fuzzy. In the above list, not all packages have translations, which is probably the reason why not everything is checked. We can go through the packages and check.
2. New packages should have force fuzzy enabled by default. Still should check though.
3. It would probably require to go back and analyze where the fuzzy is being added and why. Then, we should also check which errors would be caught if we do not force it and if it affects us.

**Comment by chriz-uniba** [comment]
wrt. point 3:

- as described here https://github.com/inveniosoftware/invenio-app-rdm/issues/230
- and tested and read in the docs:
- at least, as long as we have the `header` we get the `fuzzy`
- an alternative for this header-`fuzzy` is to use `python setup.py extract_messages --omit-header`
- but then we loose the header information
- I didn't check whether there are other ways how `fuzzy` could get in our files
- the moment a file contains `fuzzy` this file will not compiled at all anymore - without any warning or error messages (others are complaining about this, too)
- this makes it hard to detect the issue
- therefore, using `fuzzy` sounds the best way to go, for now.

```
[compile_catalog]
use-fuzzy = True   
```

wrt. point 2:

- the documentation mentions the `fuzzy`: https://inveniordm.docs.cern.ch/develop/howtos/i18n/#configuration

wrt. point 1:

I will try go through all packages and check for the `fuzzy` and report back.

**Comment by chriz-uniba** [comment]
Starting with the following:

from Pipfile.lock with invenio-app-rdm "=12.0.0b2.dev35"
all packages containing invenio in their name
- [ ] flask-collect-invenio
- [ ] flask-kvsession-invenio
- [ ] flask-security-invenio
- [ ] invenio-access
- [ ] invenio-accounts
- [ ] invenio-admin
- [ ] invenio-administration
- [ ] invenio-app
- [ ] invenio-app-rdm
- [ ] invenio-assets
- [ ] invenio-banners
- [ ] invenio-base
- [ ] invenio-cache
- [ ] invenio-celery
- [ ] invenio-communities
- [ ] invenio-config
- [ ] invenio-db
- [ ] invenio-drafts-resources
- [ ] invenio-files-rest
- [ ] invenio-formatter
- [ ] invenio-github
- [ ] invenio-i18n
- [ ] invenio-indexer
- [ ] invenio-jsonschemas
- [ ] invenio-logging
- [ ] invenio-mail
- [ ] invenio-notifications
- [ ] invenio-oaiserver
- [ ] invenio-oauth2server
- [ ] invenio-oauthclient
- [ ] invenio-pages
- [ ] invenio-pidstore
- [ ] invenio-previewer
- [ ] invenio-queues
- [ ] invenio-rdm-records
- [ ] invenio-records
- [ ] invenio-records-files
- [ ] invenio-records-permissions
- [ ] invenio-records-resources
- [ ] invenio-records-rest
- [ ] invenio-records-ui
- [ ] invenio-requests
- [ ] invenio-rest
- [ ] invenio-search
- [ ] invenio-search-ui
- [ ] invenio-stats
- [ ] invenio-theme
- [ ] invenio-userprofiles
- [ ] invenio-users-resources
- [ ] invenio-vocabularies
- [ ] invenio-webhooks

**Comment by chriz-uniba** [comment]
based on this:

have fuzzy:

- invenio-access
- invenio-accounts
- invenio-app-rdm
- invenio-banners
- invenio-communities
- invenio-drafts-resources
- invenio-formatter
- invenio-i18n
- invenio-notifications
- invenio-oaiserver
- invenio-oauth2server
- invenio-oauthclient
- invenio-pidstore
- invenio-rdm-records
- invenio-records
- invenio-records-permissions
- invenio-records-resources
- invenio-requests
- invenio-search-ui
- invenio-theme
- invenio-userprofiles
- invenio-users-resources
- invenio-vocabularies
- invenio-webhooks

no fuzzy but likely no problem:
- flask-collect-invenio
- flask-kvsession-invenio
- invenio-app
- invenio-assets
- invenio-base
- invenio-cache
- invenio-celery
- invenio-config
- invenio-db
- invenio-jsonschemas
- invenio-logging
- invenio-mail
- invenio-queues
- invenio-records-files
- invenio-rest
- invenio-search
- invenio-stats

no fuzzy and more likely a problem:

- invenio-files-rest
- invenio-github
- flask-security-invenio
- invenio-admin
- invenio-administration
- invenio-pages
- invenio-previewer

no fuzzy and maybe a problem:
- invenio-indexer
- invenio-records-rest
- invenio-records-ui

not checked

- cookiecutter-invenio-rdm
- cookiecutter-invenio-module
- marshmallow-utils

**Comment by chriz-uniba** [comment]
wrt 'no fuzzy but likely no problem:'

within each repo searched for `+(`, `format`, `gettext`, `I18N`, `i18next`, `Trans`

result:

```
flask-collect-invenio:
- found: python 'format'
- but no traces of translation intents

flask-kvsession:
- found _(...) in docs-folder
- but no traces of translation intents

invenio-app:
- found: 'gettext' and 'I18N' in documentation
- found: python 'format' in test_helpers
- but no traces of translation intents


invenio-assets:
- found: 'gettext' and 'I18N' in docs
- found: python 'format'
- but no traces of translation intents

invenio-base:
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-cache:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-celery:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-config:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-db:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-jsonschemas:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-logging:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-mail:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-queue:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents
- .tx/config:9:# TODO: Transifex integration

invenio-records-files:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-rest:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-search:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents

invenio-stats:
- found: python 'format'
- found: 'gettext' and 'I18N' in docs
- but no traces of translation intents
- .tx/config:9:# TODO: Transifex integration

```

**Comment by chriz-uniba** [comment]
All PRs are merged. For the moment we should be good. Let's close it. @zzacharo
