### ISSUE TITLE
i18n workflow: migrate transifex client

### ISSUE THREAD

**Issue by rekt-hard** [inveniosoftware/invenio-i18n#114]
The current translations workflow is broken and it is *blocked*. No new translations are being pushed/pulled to/from Transifex. This is because the API and CLI  we use are deprecated.

![image](https://user-images.githubusercontent.com/72449192/218483545-e20df7ca-2c92-46c0-af16-1a993f9e2111.png)

To fix this issue there are two possibilities:

**a) GitHub integration**

- Work to be done: configure the integration between Transifex and GitHub (see [integration guide](https://help.transifex.com/en/articles/6265125-github-via-transifex-ui)).
- Pros: translations push and pull would be done automatically, and we could remove the i18n GH action from all the modules.
- Cons: it would create one PR *per language* on each repo to update the `.tx` folder. This PRs would be periodical, and the interval can be configured, e.g. every day, week, etc.

**b) Migrate transifex workflows to use the new client and actions**

- Work to be done: explore the usage of
  - [organization wide workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows)
  - [organization required workflows](https://docs.github.com/en/actions/using-workflows/required-workflows)
so they are centralized, and update to use the new [transifex github action](https://github.com/transifex/cli-action).
- Pros: we would be in control (no random periodical PRs), we can pull only on release to update `.tx` folder in each package (e.g. maybe in the pypi GH action) and push on every merge to master, we could remove the specific GH actions (using only one organization wide).
- Cons: is not an integration, we might need to maintain a GH action (only one)

**Comment by ppanero** [comment]
After discussion, both @rekt-hard and me would favor option `b`. Mainly to avoid having bunch of PRs that need to be handled (who would do it) and risk them becoming dependabot 2.0.
