### ISSUE TITLE
tests: get Invenio running in a different language

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-i18n#5]
Test that we can run Invenio in a different language.

Likely we need better language and timezone selectors than the ones there now (possibly the need to be added in other modules).

E.g. timezone could be a preference set in a user profile as well as language.
Additionally, do we want to keep the Invenio legacy pattern of appending the language as a query string ``?ln=da``

Ping @tiborsimko @jirikuncar

**Comment by jirikuncar** [comment]
> E.g. timezone could be a preference set in a user profile as well as language.

:+1: / cc @SamiHiltunen
