### ISSUE TITLE
language doesn't change on invenio-app-ils

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/invenio-i18n#59]
![screen shot 2017-08-03 at 10 17 18 am](https://user-images.githubusercontent.com/9035606/28912558-03f93f00-7835-11e7-8472-1fce170b1638.png)

**Comment by lnielsen** [comment]
This is fixed by #58 right?

**Comment by diegodelemos** [comment]
No, it fixes the usage of inline javascript. It calls the server and so on. The Jinja template changes the focus to Français but the content is still in English

**Comment by diegodelemos** [comment]
moved to https://github.com/inveniosoftware/invenio-app-ils/issues/25
