### ISSUE TITLE
Contact Transifex for Open Source Project status.

### ISSUE THREAD

**Issue by hbayindir** [inveniosoftware/invenio-i18n#77]
Since Transifex is a for profit company, using their services is not free unless, the customer is an open source project.

Transifex allows open source software to use their service for free (see [here](https://docs.transifex.com/projects/open-source-project) for details) but, we need to contact them and tell about our status first.

They require an OSI approved open source license and, MIT seems to be an [approved license](https://opensource.org/licenses).

Seems like we are an eligible candidate, so we need to contact them.

**Comment by chriz-uniba** [comment]
This issue is from 2020. What's the status? Is there still something to do, or can we close it, either because it's done, or because it won't be done / it is not necessary anymore?

**Comment by hbayindir** [comment]
I think this issue can be closed. I think it's either solved is not necessary anymore.
