### ISSUE TITLE
i18n: How to translate a module

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-i18n#78]
### Mark strings

There are 2 ways of marking text for translation:
* Use of `_` function passing as an argument the string you want to mark for translation.For example:
```python
from flask_babelex import gettext as _
_('Test')
```
_**NOTE**_: The `_` function is already populated in your templates so you can use it directly without importing it.

* Use of the special tag `{% trans %}`/`{% endtrans %}`. For example:
```python
{% trans search_link=url_for('invenio_search_ui.search') %} <a href="{{search_link}}">Search</a> for records!{% endtrans %}
```
In this example we use string interpolation by injecting a named variable `search_link`. By doing that when we collect the marked strings for translation, the above one will be shown as:
```
msgid " <a href=\"%(search_link)s\">Search</a> for records!"
msgstr ""
```
As a result when you translate the message you just need to keep the tags as they are and focus only on the text that needs translation. The `search_link` variable will be computed dynamically on runtime with the correct value.

_**NOTE**:_ We recommend using the `{% trans %}` tag when the translation includes some html tags as in the example above. If the text is not interrupted by any other html tag the use of `_` function can be used instead.

_**NOTE**:__ If you want/need to inject more than one string inside a `{% trans %}` / `{% endtrans %}` pair, it can be done with separating the variables with a comma (`,`).
```python
{% trans search_link=url_for('invenio_search_ui.search'), deposit_link=url_for('invenio_deposit_ui.deposit') %} <a href="{{search_link}}">Search</a> or <a href="{{deposit_link}}">Deposit</a> records!{% endtrans %}
```

### Translation checklist

Iterate through the module and make sure you mark for translation the following:

* **Templates**:  Go through and mark all strings shown in the html templates
* **Views**: Go through codebase and mark for translation all views responses that are meant to be shown in the user interface. 
* **Errors**: Go through codebase and and mark for translation all the custom error responses that are meant to be shown in the user interface. **Don't translate** error keys as these are meant to be interpreted from the user interface. Translate only the text values! 

### Collect marked strings

After you have marked all the needed text in the module you should run
```python
python setup.py extract_messages
```
to collect all the marked strings. This command will update the `/translations/messages.pot` file which is the translation source file. After that you should create a `pull request` to the corresponding module with all the changes, including the files with the updated marked strings and the `messages.pot` translation source file.

### Compile catalogs
After you have extracted the marked strings and pulled the latest translations, you will need to compile the different catalogs. `Flask-BabelEx` is searching for the `.mo` files generated from the `.po` respectively by running the command:

```python
python setup.py compile_catalog
```

## Notes
- **We don't translate** api responses that include record metadata or `field names` in error/api responses.
- In general we should mark for translation **only** strings that are shown in user interface!
- For more information see the docs in [invenio-i18n](https://invenio-i18n.readthedocs.io/en/latest/usage.html#module-invenio_i18n), [flask-babelex](https://pythonhosted.org/Flask-BabelEx/#using-translations), [babel](http://babel.pocoo.org/en/latest/messages.html#working-with-message-catalogs) .

**Comment by chriz-uniba** [comment]
Can we figure out, what's the status of this issue?

- As far as I see we have the documentation "How to" in the official documentation: https://inveniordm.docs.cern.ch/develop/howtos/i18n/

- I clicked on some of the related open issues. In my small sample I saw that all related tasked were checked as finished in these issues, but still the issues stayed open.
- What's the status? Is there something to help complete it and close them? My feeling says, that it is unlikely that these translations are still missing.
