### ISSUE TITLE
i18n: investigate how to translate js templates

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-i18n#79]
We need to investigate and document the way to translate javascript UI templates/components.

**Comment by chriz-uniba** [comment]
Is that the answer: https://inveniordm.docs.cern.ch/develop/howtos/i18n/#javascript
Or do we want/need more investigation on that?

**Comment by zzacharo** [comment]
> Is that the answer: https://inveniordm.docs.cern.ch/develop/howtos/i18n/#javascript Or do we want/need more investigation on that?

Yes! I am closing this :)
