### ISSUE TITLE
search: how to deal with ES analyzers

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-i18n#80]
When indexing content in different languages it would be nice if appart from `text` the indexes use the language specific one. However, this is a challenge to set up... One possibility is through the Cookiecutter, by asking the language and templating the index (but they are in another module).

**Comment by lnielsen** [comment]
I'm closing this issue. It should be dealt with via an RFC, as it likely involves e.g. using Elasticseach DSL's Document class to create indexes.
